### ISSUE TITLE
latest game bug 

### ISSUE THREAD

**Issue by a12233** [lirex14/chessExercise#5]
```2020-03-09T19:48:40.314027+00:00 heroku[router]: at=info method=GET path="/latestGame" host=rexchessviz.herokuapp.com request_id=304a2fe2-8c4d-47d9-beb2-3e4d73abfbab fwd="198.178.12.46" dyno=web.1 connect=1ms service=3ms status=301 bytes=463 protocol=https
2020-03-09T19:48:40.691472+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'moves' of undefined
2020-03-09T19:48:40.691482+00:00 app[web.1]: at /app/server.js:136:33
2020-03-09T19:48:40.691483+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-03-09T19:48:40.691559+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2020-03-09T19:48:40.691632+00:00 app[web.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by a12233** [comment]
```       
let flag = false 
flag = await insertGame(id, moves, color);
if(flag) { resolve(id) }
```

`const data = await pool.query('SELECT * FROM mygames WHERE id=$1', [id]); `

Insert and select into postgres has a potential race condition. Second time the page loads, select returns the correct row.

**Comment by a12233** [comment]
resolved, with async await on INSERT
